services:
  - type: web
    name: digit-recognition-app
    runtime: python
    buildCommand: pip install \
      Flask==3.1.1 \
      tensorflow==2.10.1 \
      numpy==1.23.5 \
      Pillow==10.3.0 \
      Werkzeug==2.3.8 \
      scikit-learn==1.4.2 \
      matplotlib==3.8.4
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
